# configure file for ATACqPCR pipeline based on pypiper
#system configure
tools:

# basic tools 
  Rscript: Rscript
  # absolute paths to required tools

# public tools 
  samtools:  samtools
  bedtools: bedtools #version 2
  fetchChromSizes: fetchChromSizes
# private tools
  make_window_bed: <ATACqPCRdir>/scripts/make_window_bed.R
  find_qPCR_regions: <ATACqPCRdir>/scripts/find_qPCR_regions.R
  

#User configure 
resources:
  genomes: <ATACqPCRdir>/genomes/      

parameters:
  # parameters passed to bioinformatic tools, subclassed by tool
  samtools:
         q: 10

