# configure file for ATACPrimerTool based on pypiper
#system configure
tools:

# basic tools 
  Rscript: Rscript
  # absolute paths to required tools

# public tools 
  samtools:  samtools
  bedtools: bedtools
  fetchChromSizes: fetchChromSizes
# private tools
  make_window_bed: <APTdir>/scripts/make_window_bed.R
  find_qPCR_regions: <APTdir>/scripts/find_qPCR_regions.R
  

#User configure 
resources:
  genomes: <APTdir>/genomes/      

parameters:
  # parameters passed to bioinformatic tools, subclassed by tool
  samtools:
         q: 10

