# configure file for norm_peaks pipeline based on pypiper
#system configure
tools:

# basic tools 
  Rscript: Rscript #if not in path, use /pathto/Rscript
# public tools 
  samtools:  samtools #if not in path, use /pathto/samtools
  bedtools: bedtools #if not in path, use /pathto/bedtools
  macs2: macs2 #if not in path, use /pathto/macs2
  annotate_peaks: annotatePeaks.pl #if not in path, use /pathto/annotatePeaks.pl
# private tools
  bam2bed_shift: <APTdir>/scripts/bam2bed_shift.pl
  norm_counts: <APTdir>/scripts/normpeaks.R
  mergePeaks: <APTdir>/scripts/mergePeaks.pl
#User configure
resources:
  genomes: <APTdir>/genomes/

parameters:
  # parameters passed to bioinformatic tools, subclassed by tool
  
  samtools:
         q: 10
  macs2: 
         f: BED
         q: 0.01
         shift: 0 

