ATACPrimerTool.py:
  name: ATACqPCR
  looper_args: False
  arguments:
    "--sample-name": sample_name
    "--genome": genome
    "--input": bam_dir
    "--input2": peak_file
    "--input3": corr_cutoff
    "--input4": cov_cutoff
    "--input5": percent_overlap
    "--input6": return_seq
    "--input7": bedpe_input
    "--input8": read_counts 
  resources:
    default:
      file_size: "0"
      cores: "8"
      mem: "32000"
      time: "2-00:00:00"
      partition: "longq"
